SELECT A.MEMBER_NAME, B.REVIEW_TEXT, SUBSTR(B.REVIEW_DATE, 1, 10) AS REVIEW_DATE
FROM MEMBER_PROFILE AS A
    JOIN REST_REVIEW AS B
    ON A.MEMBER_ID = B.MEMBER_ID
WHERE A.MEMBER_ID = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC 
    LIMIT 1
)
ORDER BY REVIEW_DATE ASC, REVIEW_TEXT;