SELECT REV.REST_ID, 
    INF.REST_NAME, 
    INF.FOOD_TYPE, 
    INF.FAVORITES, 
    INF.ADDRESS, 
    ROUND(AVG(REV.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW AS REV
    JOIN REST_INFO AS INF
    ON REV.REST_ID = INF.REST_ID
WHERE INF.ADDRESS REGEXP '^서울'
GROUP BY REV.REST_ID
ORDER BY SCORE DESC, INF.FAVORITES DESC;