SELECT 
    BOOK.AUTHOR_ID, 
    AUTHOR_NAME,
    CATEGORY,
    SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK
    JOIN AUTHOR
    ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    JOIN BOOK_SALES AS SALES
    ON BOOK.BOOK_ID = SALES.BOOK_ID
WHERE SALES.SALES_DATE REGEXP '^2022-01'
GROUP BY BOOK.CATEGORY, BOOK.AUTHOR_ID
ORDER BY BOOK.AUTHOR_ID, BOOK.CATEGORY DESC;