SELECT USR.USER_ID, USR.NICKNAME, SUM(BRD.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS BRD
    JOIN USED_GOODS_USER AS USR
    ON BRD.WRITER_ID = USR.USER_ID
WHERE BRD.STATUS = 'DONE'
GROUP BY USR.USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES ASC;